name: Custom Fetch and Push

on:
  workflow_dispatch:
   inputs:
      page-url:
        description: 'URL of the page to crawl'
      entity-identifier:
        description: 'Identifier of the entity'
      artifact:
        description: 'name of artifact'
      publisher:
        description: 'publisher id'
        
      
jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v3
        with:
          mode: "fetch-push"
          artifact: "${{ inputs.artifact }}"
          publisher: "${{ inputs.publisher  }}"
          downloadFile: "output/${{ inputs.artifact }}.jsonld"
          page-url: "${{ inputs.page-url }}"
          entity-identifier: "${{ inputs.entity-identifier }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
          cloudflare-private-key: ${{ secrets.CLOUDFLARE_PRIVATE_KEY }}
