name: Fetch Agoradanse Events - spider test
on:
  workflow_dispatch:
  schedule:
  - cron: 0 0 1 * *
jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Action setup
      uses: culturecreates/artsdata-pipeline-action@v3
      with:
        mode: fetch-push
        artifact: agoradanse-com
        publisher: "${{ secrets.PUBLISHER_URI_GREGORY }}"
        downloadFile: output/agoradanse-events.jsonld
        page-url: https://agoradanse.com
        headless: true
        token: "${{ secrets.GITHUB_TOKEN }}"
        custom-databus-url: "http://staging.api.artsdata.ca/databus/"
