name: Fetch capitol-nb-ca Events - spider test

on:
  workflow_dispatch:

jobs:
  artsdata-fetch-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Action setup
        uses: culturecreates/artsdata-pipeline-action@v3
        with:
          mode: "fetch-push"
          artifact: "capitol-nb-ca"
          publisher: "${{ secrets.PUBLISHER_URI_GREGORY }}"
          downloadFile: "output/capitolnb-events.jsonld"
          page-url: "https://capitol.nb.ca"
          token: "${{ secrets.GITHUB_TOKEN }}"
          custom-databus-url: "http://staging.api.artsdata.ca/databus/"
